version: '3.8'

services:
  mongodb:
    image: mongo:latest
    hostname: "mongodb-dev"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - default

  article:
    image: articleserviceapi
    environment:
      - UsersDatabase=Users
      - UserCollection=user
      - AuctionHouseCollection=auctionhouse
      - InventoryDatabase=Inventory
      - ArticleCollection=article
      - ConnectionURI=mongodb://admin:1234@mongodb-dev:27017/?authSource=admin
    ports:
      - 5002:80
    depends_on:
      - mongodb
    healthcheck:
      retries: 5
    networks:
      - default

volumes:
  mongodb_data_container:

networks:
  default:
    driver: bridge
