version: '3.8'

services:
  articleservice:
    image: gitpushers/article-service:latest-dev
    container_name: article
    environment:
      - HostnameVault=jacob
      - ImagePath=/srv/images/
      - UsersDatabase=Users
      - UserCollection=user
      - AuctionHouseCollection=auctionhouse
      - InventoryDatabase=Inventory
      - ArticleCollection=article
    expose:
      - "80"
    healthcheck:
      retries: 5
    networks:
      - sharednetwork
    volumes:
      - article-image-storage:/srv/images

  userservice:
    image: gitpushers/users-service:latest-dev
    container_name: user
    environment:
      - HostnameVault=jacob
      - UsersDatabase=Users
      - UserCollection=user
    expose:
      - "80"
    healthcheck:
      retries: 5
    networks:
      - sharednetwork

  auctionplanningservice:
    image: gitpushers/auctionplanning-service:latest-dev
    container_name: auctionplanning
    environment:
      - HostnameVault=jacob
      - AuctionsDatabase=Auctions
      - AuctionCollection=listing
      - InventoryDatabase=Inventory
      - ArticleCollection=article
    expose:
      - "80"
    healthcheck:
      retries: 5
    networks:
      - sharednetwork

  authentication:
    image: gitpushers/auth-service:latest-dev
    container_name: authentication
    environment:
      - UsersDatabase=Users
      - UserCollection=user
      - HostnameVault=jacob
    expose:
      - "80"
    healthcheck:
      retries: 5
    networks:
      - sharednetwork

  auctionservice:
    image: gitpushers/auction-service:latest-dev
    container_name: auctionservice
    environment:
      - HostnameVault=jacob
      - HostnameRabbit=rabbitmq-dev
      - UsersDatabase=Users
      - UserCollection=user
      - AuctionHouseCollection=auctionhouse
      - InventoryDatabase=Inventory
      - ArticleCollection=article
      - AuctionsDatabase=Auctions
      - AuctionCollection=listing
    expose:
      - "80"
    networks:
      - sharednetwork
    restart: on-failure

  bidworkerservice:
    image: gitpushers/bidengine-service:latest-dev
    container_name: bidworkerservice
    environment:
      - HostnameRabbit=rabbitmq-dev
      - HostnameVault=jacob
      - AuctionsDatabase=Auctions
      - UsersDatabase=Users
      - AuctionCollection=listing
      - UserCollection=user
    expose:
      - "80"
    networks:
      - sharednetwork
    healthcheck:
        retries: 5
    restart: on-failure

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - articleservice
      - userservice
      - auctionplanningservice
      - authentication
      - auctionservice
      - bidworkerservice
    healthcheck:
        retries: 5
    ports:
      - "4000:4000"
    networks:
      - sharednetwork

volumes:
  article-image-storage:
    external: false

networks:
  sharednetwork:
    driver: bridge
    external: true
