version: '3.8'

services:
  mongodb:
    image: mongo:latest
    hostname: "mongodb-dev"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - default

volumes:
  mongodb_data_container:

networks:
  default:
    driver: bridge
