version: '3.8'

services:
  mongodb:
    image: mongo:latest
    hostname: "mongodb-dev"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - default

  articleservice:
    image: gitpushers/article-service:latest-dev
    container_name: article
    environment:
      - HostnameVault=jacob
      - ImagePath=/srv/images/
      - UsersDatabase=Users
      - UserCollection=user
      - AuctionHouseCollection=auctionhouse
      - InventoryDatabase=Inventory
      - ArticleCollection=article
    expose:
      - "80"
    depends_on:
      - script
    healthcheck:
      retries: 5
    networks:
      - default
    volumes:
      - article-image-storage:/srv/images

  userservice:
    image: gitpushers/users-service:latest-dev
    container_name: user
    environment:
      - HostnameVault=jacob
      - UsersDatabase=Users
      - UserCollection=user
    expose:
      - "80"
    depends_on:
      - script
    healthcheck:
      retries: 5
    networks:
      - default

  auctionplanningservice:
    image: gitpushers/auctionplanning-service:latest-dev
    container_name: auctionplanning
    environment:
      - HostnameVault=jacob
      - AuctionsDatabase=Auctions
      - AuctionCollection=listing
      - InventoryDatabase=Inventory
      - ArticleCollection=article
    expose:
      - "80"
    depends_on:
      - script
    healthcheck:
      retries: 5
    networks:
      - default

  authentication:
    image: gitpushers/auth-service:latest-dev
    container_name: authentication
    environment:
      - UsersDatabase=Users
      - UserCollection=user
      - HostnameVault=jacob
    expose:
      - "80"
    depends_on:
      - script
    healthcheck:
      retries: 5
    networks:
      - default

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - default
    volumes:
      - grafana-storage:/var/lib/grafana

  vault_dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:10
    hostname: jacob
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address":"0.0.0.0:8201","tls_disable":"0", "tls_cert_file":"/data/cert.pem","tls_key_file":"/data/key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-volume:/data
    healthcheck:
      retries: 5
    command: sh -c "export VAULT_ADDR='http://127.0.0.1:8200' && export VAULT='http://0.0.0.0:8201' && vault server -dev -dev-root-token-id='00000000-0000-0000-0000-000000000000'"

  script:
    image: hashicorp/vault:latest
    command: sh "/app/populate_vault.sh"
    depends_on:
      - vault_dev
    healthcheck:
      retries: 5
    volumes:
      - ./populate_vault.sh:/app/populate_vault.sh

  rabbitmq:
    image: rabbitmq:management
    hostname: "rabbitmq-dev"
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 10s
      timeout: 10s
      retries: 5

  auctionservice:
    image: gitpushers/auction-service:latest-dev
    container_name: auctionservice
    environment:
      - HostnameVault=jacob
      - HostnameRabbit=rabbitmq-dev
      - UsersDatabase=Users
      - UserCollection=user
      - AuctionHouseCollection=auctionhouse
      - InventoryDatabase=Inventory
      - ArticleCollection=article
      - AuctionsDatabase=Auctions
      - AuctionCollection=listing
    expose:
      - "80"
    networks:
      - default
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  bidworkerservice:
    image: gitpushers/bidengine-service:latest-dev
    container_name: bidworkerservice
    environment:
      - HostnameRabbit=rabbitmq-dev
      - ConnectionURI=mongodb://admin:1234@mongodb-dev:27017/?authSource=admin
    expose:
      - "80"
    networks:
      - default
    healthcheck:
        retries: 5
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - articleservice
      - userservice
      - auctionplanningservice
      - authentication
      - auctionservice
      - bidworkerservice
    healthcheck:
        retries: 5
    ports:
      - "4000:4000"

volumes:
  mongodb_data_container:
  grafana-storage:
    external: false
  article-image-storage:
    external: false

networks:
  default:
    driver: bridge
