version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: "rabbitmq-dev"
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 10s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:latest
    hostname: "mongodb-dev"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - default

  maintenance:
    image: auctionserviceapi
    container_name: auctionservice
    environment:
      - ConnectionURI=mongodb://admin:1234@mongodb-dev:27017/?authSource=admin
      - HostnameRabbit=rabbitmq-dev
    ports:
      - 5001:80
    networks:
      - default
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

  bidworkerservice:
    image: bidworker
    container_name: bidworker
    environment:
      - HostnameRabbit=rabbitmq-dev
      - ConnectionURI=mongodb://admin:1234@mongodb-dev:27017/?authSource=admin
    ports:
      - 5002:80
    networks:
      - default
    healthcheck:
        retries: 5
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  mongodb_data_container:


networks:
  default:
    driver: bridge
